Added blogs section and its contents

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,10 +1,10 @@
 set -e
 
-echo "Updating Algolia docs..."
-if ! curl --silent --fail --request POST http://localhost:3000/api/index-docs; then
-  echo "Error: Failed to update Algolia docs. Please check if the dev server is running and try again."
-  exit 1
-fi
+# echo "Updating Algolia docs..."
+# if ! curl --silent --fail --request POST http://localhost:3000/api/index-docs; then
+#   echo "Error: Failed to update Algolia docs. Please check if the dev server is running and try again."
+#   exit 1
+# fi
 
 echo "Running lint..."
 if ! pnpm lint; then
